/** '.' is transparent; every other character is a PALETTE key. */
export const PALETTE: Record<string, string> = {
  r: '#d82800', // red
  s: '#fc9838', // skin
  b: '#a85800', // brown
  d: '#7c3c00', // dark brown
  k: '#000000', // black
  w: '#ffffff', // white
  y: '#fcbc3c', // yellow
  o: '#c84c0c', // orange
  g: '#58d854', // light green
  G: '#00a800', // green
  u: '#0058f8', // blue
};

export const SPRITES = {
  playerSmallStand: [
    '..rrrr..',
    '.rrrrrr.',
    '.ssksks.',
    '.ssssss.',
    '..rrrr..',
    '.rrbbrr.',
    '.rr..rr.',
    '.bb..bb.',
  ],
  playerSmallRun: [
    '..rrrr..',
    '.rrrrrr.',
    '.ssksks.',
    '.ssssss.',
    '.rrrrrr.',
    'rr.bb.rr',
    '..bbbb..',
    '.bb..bb.',
  ],
  playerSmallJump: [
    '..rrrr..',
    '.rrrrrr.',
    '.ssksks.',
    's.ssss.s',
    's.rrrr.s',
    '..rrrr..',
    '.bb..bb.',
    'bb....bb',
  ],
  playerBigJump: [
    '..rrrr..',
    '.rrrrrr.',
    '.rrrrrr.',
    '.ssksks.',
    '.ssssss.',
    '.sssss..',
    's.rrrr.s',
    's.rrrr.s',
    's.rrrr.s',
    '..bbbb..',
    '..bbbb..',
    '.bbb.bbb',
    'bbb...bb',
    'bb.....b',
    'bb.....b',
    'dd.....d',
  ],
  playerBigStand: [
    '..rrrr..',
    '.rrrrrr.',
    '.rrrrrr.',
    '.ssksks.',
    '.ssssss.',
    '.sssss..',
    '..rrrr..',
    '.rrrrrr.',
    'rrbrrbrr',
    'rrbbbbrr',
    'ssbbbbss',
    '.bbbbbb.',
    '.bbbbbb.',
    '.bb..bb.',
    '.bb..bb.',
    'dd....dd',
  ],
  playerBigRun: [
    '..rrrr..',
    '.rrrrrr.',
    '.rrrrrr.',
    '.ssksks.',
    '.ssssss.',
    '.sssss..',
    '..rrrr..',
    '.rrrrrr.',
    'rrrbbrrr',
    'ss.bbb.s',
    '..bbbbb.',
    '.bbbbbb.',
    '.bbb.bbb',
    'bbb...bb',
    'bb.....b',
    'dd.....d',
  ],
  walker: [
    '..dddd..',
    '.dddddd.',
    'dddddddd',
    'dwkddkwd',
    'dddddddd',
    '.dddddd.',
    '..ssss..',
    '.kk..kk.',
  ],
  turtle: [
    '...gg...',
    '..gsg...',
    '..gggg..',
    '.GGgGgG.',
    'GgGGGGgG',
    'GGGGGGGG',
    '.yyyyyy.',
    '.yy..yy.',
  ],
  shell: [
    '........',
    '..GGGG..',
    '.GgGgGG.',
    'GgGGGGgG',
    'GGGGGGGG',
    '.wwwwww.',
    '..wwww..',
    '........',
  ],
  ground: [
    'gggggggg',
    'GGGGGGGG',
    'bbbbbbbb',
    'bdbbbbdb',
    'bbbbdbbb',
    'bbbbbbbb',
    'dbbbbbdb',
    'bbbdbbbb',
  ],
  brick: [
    'dddddddd',
    'oooodooo',
    'oooodooo',
    'dddddddd',
    'ooodoooo',
    'ooodoooo',
    'dddddddd',
    'oooodooo',
  ],
  question: [
    'dyyyyyyd',
    'ykkkkkky',
    'ykyyyyky',
    'yyyyykky',
    'yyykkyyy',
    'yyykyyyy',
    'yyyyyyyy',
    'dyyyyyyd',
  ],
  used: [
    'dddddddd',
    'dbbbbbbd',
    'dbbbbbbd',
    'dbbbbbbd',
    'dbbbbbbd',
    'dbbbbbbd',
    'dbbbbbbd',
    'dddddddd',
  ],
  mushroom: [
    '..rrrr..',
    '.rwrrwr.',
    'rrwrrwrr',
    'rrrrrrrr',
    '.wwssww.',
    '..wssw..',
    '..wssw..',
    '...ww...',
  ],
  coin: [
    '...yy...',
    '..yooy..',
    '..yooy..',
    '..yooy..',
    '..yooy..',
    '..yooy..',
    '..yooy..',
    '...yy...',
  ],
  pipeTL: [
    'kkkkkkkk',
    'kggGGGGG',
    'kggGGGGG',
    'kkkkkkkk',
    '.kggGGGG',
    '.kggGGGG',
    '.kggGGGG',
    '.kggGGGG',
  ],
  pipeTR: [
    'kkkkkkkk',
    'GGGGGGGk',
    'GGGGGGGk',
    'kkkkkkkk',
    'GGGGGGk.',
    'GGGGGGk.',
    'GGGGGGk.',
    'GGGGGGk.',
  ],
  pipeL: [
    '.kggGGGG',
    '.kggGGGG',
    '.kggGGGG',
    '.kggGGGG',
    '.kggGGGG',
    '.kggGGGG',
    '.kggGGGG',
    '.kggGGGG',
  ],
  pipeR: [
    'GGGGGGk.',
    'GGGGGGk.',
    'GGGGGGk.',
    'GGGGGGk.',
    'GGGGGGk.',
    'GGGGGGk.',
    'GGGGGGk.',
    'GGGGGGk.',
  ],
  warpBlock: [
    'kkkkkkkk',
    'kggGGGGk',
    'kggGGGGk',
    'kkkkkkkk',
    'kggGGGGk',
    'kggGGGGk',
    'kGGGGGGk',
    'kkkkkkkk',
  ],
  mushroomOneUp: [
    '..GGGG..',
    '.GwGGwG.',
    'GGwGGwGG',
    'GGGGGGGG',
    '.wwssww.',
    '..wssw..',
    '..wssw..',
    '...ww...',
  ],
} as const satisfies Record<string, readonly string[]>;

export type SpriteName = keyof typeof SPRITES;
